# Generated by Django 4.0.3 on 2022-08-23 06:39

import Extentions.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام بانک')),
                ('card_number', models.BigIntegerField(verbose_name='شماره کارت')),
                ('stock', models.FloatField(verbose_name='موجودی')),
            ],
            options={
                'verbose_name': 'کارت بانکی',
                'verbose_name_plural': 'کارت های بانکی',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProfileCollectorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(blank=True, null=True, upload_to=Extentions.utils.user_image_path, verbose_name='پروفایل')),
            ],
            options={
                'verbose_name': 'جمع آورنده ی پروفایل',
                'verbose_name_plural': 'جمع آورنده ی پروفایل کاربران',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='VersionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=255, verbose_name='ورژن')),
                ('description', models.TextField(verbose_name='توضیحات ورژن')),
            ],
            options={
                'verbose_name': 'ورژن',
                'verbose_name_plural': 'ورژن\u200cها',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='مبلغ')),
                ('in_out', models.CharField(choices=[('withdrawal', 'برداشت'), ('deposit', 'واریز')], max_length=20, verbose_name='واریز یا برداشت؟')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('time', models.TimeField(verbose_name='زمان')),
                ('date', models.DateField(blank=True, null=True, verbose_name='تاریخ')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.bankmodel', verbose_name='کارت بانکی')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش ها',
                'ordering': ['-id'],
            },
        ),
    ]
